/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.employeepayrollservice;

import java.time.LocalDate;

public class EmployeePayrollData {

		public int id;
		public String name;
		public double salary;
		public LocalDate startDate;

		public EmployeePayrollData(int id, String name, double salary) {
			this.id = id;
			this.name = name;
			this.salary = salary;
		}

		public EmployeePayrollData(int id, String name, Double salary, LocalDate startDate) {
			this.id = id;
	        this.name = name;
	        this.salary = salary;
	        this.startDate = startDate;
		}

		@Override
		public String toString() {
			  return "id=" + id + ", name=" + name + ", salary=" + salary;
		}
}

