/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.employeepayrollservice;

public class EmployeePayrollData {

		public int id;
		public String name;
		public double salary;

		public EmployeePayrollData(int id, String name, double salary) {
			this.id = id;
			this.name = name;
			this.salary = salary;
		}

		@Override
		public String toString() {
			return "Employee Data [id=" + id + ", name=" + name + ", salary=" + salary + "]";
		}
}

